from __future__ import annotations
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
MODEL_PATH = ROOT / "src" / "model" / "ctxtrace-model.json"
TS_PATH = MODEL_PATH.with_suffix(".generated.ts")
def main() -> int:
    model = json.loads(MODEL_PATH.read_text())
    ts = (
        "// AUTO-GENERATED by backend/python/gen_model_ts.py -- do not edit by hand.\n"
        f"// {model['version']}\n"
        "export interface CtxtraceModel {\n"
        "  version: string;\n"
        "  architecture: \"logistic\" | \"mlp\";\n"
        "  weights?: number[];\n"
        "  bias?: number;\n"
        "  layers?: { W: number[][]; b: number[] }[];\n"
        "  featureOrder: string[];\n"
        "  clipFeatureOrder: string[];\n"
        "  mu: number[];\n"
        "  sigma: number[];\n"
        "  threshold: number;\n"
        "  evaluation: Record<string, unknown>;\n"
        "}\n\n"
        f"export const CTXTRACE_MODEL: CtxtraceModel = {json.dumps(model)};\n"
    )
    TS_PATH.write_text(ts)
    print(f"generated: {TS_PATH}")
    return 0
if __name__ == "__main__":
    raise SystemExit(main())
